# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Continuity
version:      0.2
version_from: lib/Continuity.pm
installdirs:  site
requires:
    Contize:                       0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
