---
abstract: 'Abstract away statelessness of HTTP, for stateful Web applications'
author:
  - 'Brock Wilcox <awwaiid@thelackthereof.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by:  and then some'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Continuity
no_index:
  directory:
    - t
    - inc
requires:
  Coro: '4.37'
  Coro::Event: '0'
  Event: '0'
  HTTP::Daemon: '1.36'
resources:
  repository: https://github.com/awwaiid/continuity
version: '1.6'
