--- #YAML:1.0
name:                Continuity
version:             0.96
abstract:            Abstract away statelessness of HTTP, for stateful Web applications
license:             ~
author:              
    - Brock Wilcox <awwaiid@thelackthereof.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Coro:                          3.6
    Coro::Event:                   2.1
    HTTP::Daemon:                  1.36
    Module::Reload:                1.07
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
