--- #YAML:1.0
name:                Continuity
version:             0.996
abstract:            Abstract away statelessness of HTTP, for stateful Web applications
license:             perl
author:              
    - Brock Wilcox <awwaiid@thelackthereof.org>
generated_by:        ExtUtils::MakeMaker version 6.42 and then some
distribution_type:   module
requires:     
    Event:                         0
    Coro:                          4.37
    Coro::Event:                   0
    HTTP::Daemon:                  1.36
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
