# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Continuity
version:      0.7
version_from: lib/Continuity.pm
installdirs:  site
requires:
    Coro:                          1
    Data::Alias:                   0.01
    HTTP::Daemon:                  1.36
    HTTP::Request::AsCGI:          0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
